##### dockerfile #####

FROM nginx:latest

#
#COPY ./conf.d/nginx.conf /etc/nginx/nginx.conf
COPY ./conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./conf.d/plura_docker.conf /etc/nginx/conf.d/plura_docker.conf

# Docker Host
EXPOSE 80

# Run for Background
ENTRYPOINT ["nginx","-g","daemon off;"]
